<a href="https://colab.research.google.com/github/SeryeongLee/-/blob/main/0531_credit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install category_encoders

     |████████████████████████████████| 81kB 4.0MB/s 


In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import os
import re

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import BaggingRegressor

from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV 
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.utils import shuffle
from scipy.special import erfc
from sklearn.dummy import DummyRegressor
from sklearn.svm import SVR

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.model_selection import train_test_split, cross_validate, RandomizedSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, RandomForestRegressor, VotingRegressor

from lightgbm import LGBMRegressor

import xgboost as xgb
from xgboost import XGBClassifier, XGBRegressor

import warnings

from category_encoders.ordinal import OrdinalEncoder

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
train = pd.read_csv('/content/drive/MyDrive/creditcard/open/train.csv')
test = pd.read_csv('/content/drive/MyDrive/creditcard/open/test.csv')

## 기본 변환

#### 1) 0, 1 변환

#### 2) 수 변환

In [ ]:
# 음수 -> 양수 변환

train.DAYS_BIRTH = -train.DAYS_BIRTH
test.DAYS_BIRTH = -test.DAYS_BIRTH

train.DAYS_EMPLOYED = -train.DAYS_EMPLOYED
test.DAYS_EMPLOYED = -test.DAYS_EMPLOYED

train.begin_month = -train.begin_month
test.begin_month = -test.begin_month

In [ ]:
# 365243 인 값 0으로 바꾸기

train.DAYS_EMPLOYED = train.DAYS_EMPLOYED.replace([-365243],[0])
test.DAYS_EMPLOYED = test.DAYS_EMPLOYED.replace([-365243],[0])

In [ ]:
# 360으로 나눠서 나이, 일한 년수 계산

train['EMPLOYED']= train.DAYS_EMPLOYED.apply(lambda x: abs(x/360) )
train['age']= train.DAYS_BIRTH.apply(lambda x: abs(x/360) ).astype(int)
train['begin_month']= train.begin_month.apply(lambda x: abs(x) ).astype(int)

test['EMPLOYED']= test.DAYS_EMPLOYED.apply(lambda x: abs(x/360) )
test['age']= test.DAYS_BIRTH.apply(lambda x: abs(x/360) ).astype(int)
test['begin_month']= test.begin_month.apply(lambda x: abs(x) ).astype(int)

#### 3) 로그변환

In [ ]:
tr_it=train['income_total']
tr_it_log = np.log1p(tr_it)
train['income_total']= tr_it_log
te_it=test['income_total']
te_it_log = np.log1p(te_it)
test['income_total']= te_it_log

In [ ]:
train['EMPLOYED']= np.log1p(train['EMPLOYED'])
test['EMPLOYED']= np.log1p(test['EMPLOYED'])

#### 4) child_num, family_size 관련 컬럼 추가

In [ ]:
train['child_num'].value_counts()

0     18340
1      5386
2      2362
3       306
4        47
5        10
14        3
7         2
19        1
Name: child_num, dtype: int64

In [ ]:
# child_num이 14, 19인 행 지우기

idx_child_drop = train[(train['child_num'] == 14)|(train['child_num'] == 19)].index
train = train.drop(idx_child_drop)

In [ ]:
# child_num이 family_size보다 큰 행도 지우기

idx_child_drop2 = train[train['family_size'] < train['child_num']].index
train = train.drop(idx_child_drop2)

In [ ]:
train['cf_ratio'] = train['child_num'] / train['family_size']
test['cf_ratio'] = test['child_num'] / test['family_size']

# train['if_ratio'] = train['income_total'] / train['family_size']
# test['if_ratio'] = test['income_total'] / test['family_size']

In [ ]:
train['family_size'].value_counts()

2.0    14106
1.0     5108
3.0     4632
4.0     2260
5.0      291
6.0       44
7.0        9
9.0        2
Name: family_size, dtype: int64

In [ ]:
# family_size > 7 인 것도 지우기
train = train[(train['family_size']<=7)]
train = train.reset_index(drop=True)

#### 5) 결측치 채우기 - unemployed 만들고 nan 처리

In [ ]:
def unemployed(data):
  data.loc[(data['DAYS_EMPLOYED'] == 0), 'occyp_type'] = 'unemployed'

unemployed(train)
unemployed(test)

In [ ]:
train.fillna('Nan', inplace=True)
test.fillna('Nan',inplace=True)


In [ ]:
train.head()

index gender car reality  ...  credit  EMPLOYED age  cf_ratio
0      0      F   N       N  ...     1.0  2.644795  38  0.000000
1      1      F   N       Y  ...     1.0  1.663505  31  0.333333
2      2      M   Y       Y  ...     2.0  2.589016  53  0.000000
3      3      F   N       Y  ...     0.0  1.918555  41  0.000000
4      4      F   Y       Y  ...     2.0  1.923843  41  0.000000

[5 rows x 23 columns]

#### 명목형 변수 처리 - OrdinalEncoder

In [ ]:
encoder = OrdinalEncoder()

In [ ]:
cate_feature = train.dtypes[train.dtypes == 'object'].index.tolist()
print(len(cate_feature))
print(train.dtypes)

8
index              int64
gender            object
car               object
reality           object
child_num          int64
income_total     float64
income_type       object
edu_type          object
family_type       object
house_type        object
DAYS_BIRTH         int64
DAYS_EMPLOYED      int64
FLAG_MOBIL         int64
work_phone         int64
phone              int64
email              int64
occyp_type        object
family_size      float64
begin_month        int64
credit           float64
EMPLOYED         float64
age                int64
cf_ratio         float64
dtype: object


In [ ]:
train[cate_feature] = encoder.fit_transform(train[cate_feature],train['credit'])
test[cate_feature] = encoder.fit_transform(test[cate_feature])

/usr/local/lib/python3.7/dist-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


In [ ]:
train = train.drop(['index', 'FLAG_MOBIL', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'child_num','cf_ratio'], axis = 1)

In [ ]:
train.head()

gender  car  reality  income_total  ...  begin_month  credit  EMPLOYED  age
0       1    1        1     12.218500  ...            6     1.0  2.644795   38
1       1    1        2     12.419170  ...            5     1.0  1.663505   31
2       2    2        2     13.017005  ...           22     2.0  2.589016   53
3       1    1        2     12.218500  ...           37     0.0  1.918555   41
4       1    2        2     11.967187  ...           26     2.0  1.923843   41

[5 rows x 17 columns]

In [ ]:
# 간단한 autoencoder 모델 구현

AutoEncoder + NN 구현

* 입출력이 같은 구조
* input data를 잘 복원한다.



In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model

인코더 작성

In [ ]:
input_dim = Input(shape=(16,)) # 입력 채널 수: 16

In [ ]:
encoder1 = Dense(8, activation = 'relu')(input_dim)
encoder2 = Dense(3, activation = 'relu')(encoder1)

In [ ]:
decoder1 = Dense(8, activation='relu')(encoder2)
decoder2 = Dense(16, activation='relu')(decoder1)

모델 작성 및 컴파일

In [ ]:
autoencoder = Model(inputs = input_dim, outputs = decoder2)


In [ ]:
autoencoder.compile(optimizer = 'adam', loss = 'binary_crossentropy')

In [ ]:
train_y = train['credit']
train_x = train.drop("credit", axis = 1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(train_x, train_y,
                 stratify = train_y, 
                 test_size = 0.2,
                 random_state = 10086
                 )


In [ ]:
autoencoder.fit(x_train, x_train, batch_size= 32, shuffle= True, validation_data = (x_test,x_test))

662/662 [==============================] - 2s 2ms/step - loss: 65.9169 - val_loss: 60.6431


딥러닝 

In [ ]:
import tensorflow as tf
from tensorflow import feature_column
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

tf.data를 사용해 입력 파이프라인 만들기

In [ ]:
train.fillna('Nan',inplace=True)
test.fillna('Nan',inplace=True)


In [ ]:
# 딥러닝 모델 구현 위해 train dataset으로 train, test, val 나누기
temp_train, temp_test = train_test_split(train, test_size = 0.2)
temp_train, temp_val = train_test_split(train, test_size = 0.2)
print(len(temp_train), 'train examples')
print(len(temp_val), 'validation examples')
print(len(temp_test), 'test examples')


21165 train examples
5292 validation examples
5292 test examples


In [ ]:
d_train = train.copy()

In [ ]:
def df_to_dataset(d_train,shuffle=True,batch_size = 32):
  labels = d_train.pop('credit')
  ds = tf.data.Dataset.from_tensor_slices((dict(d_train), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size = len(d_train))
    ds = ds.batch(batch_size)
    ds = ds.prefetch(batch_size)
    return ds


In [ ]:
batch_size = 5
train_ds = df_to_dataset(temp_train, batch_size=batch_size)

In [ ]:
[(train_features, label_batch)] = train_ds.take(1)
print('Every feature:', list(train_features.keys()))
print('A batch of targets:', label_batch)

Every feature: ['index', 'gender', 'car', 'reality', 'child_num', 'income_total', 'income_type', 'edu_type', 'family_type', 'house_type', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'FLAG_MOBIL', 'work_phone', 'phone', 'email', 'occyp_type', 'family_size', 'begin_month']
A batch of targets: tf.Tensor([2. 2. 2. 2. 2.], shape=(5,), dtype=float64)


전처리 레이어의 사용 시연

1. 숫자 열

In [ ]:
def get_normalization_layer(name, dataset):
  normalizer = preprocessing.Normalization()
  feature_ds = dataset.map(lambda x, y: x[name])
  normalizer.adapt(feature_ds)
  return normalizer

In [ ]:
income_total_col = train_features['income_total']
layer = get_normalization_layer('income_total', train_ds)
layer(income_total_col)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 0.36945453],
       [-0.07058038],
       [ 1.2495244 ],
       [ 0.14943708],
       [-0.5106153 ]], dtype=float32)>

숫자 특성이 많은 경우, 먼저 숫자 특성을 연결하고 단일 normalization 레이어를 사용하는 것이 더 효율적

2. 범주 열

In [ ]:
def get_category_encoding_layer(name, dataset, dtype, max_tokens = None):
  if dtype == 'string':
    index = preprocessing.StringLookup(max_tokens=max_tokens)
  else:
    index = preprocessing.IntegerLookup(max_values = max_tokens)
  feature_ds = dataset.map(lambda x, y: x[name])
  index.adapt(feature_ds)
  encoder = preprocessing.CategoryEncoding(max_tokens = index.vocabulary_size())
  feature_ds = feature_ds.map(index)
  encoder.adapt(feature_ds)
  return lambda feature: encoder(index(feature))

In [ ]:
gender_col = train_features['gender']
layer = get_category_encoding_layer('gender', train_ds, 'string')
layer(gender_col)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

사용할 열 선택 - 열 몇개만 이용해서 구현  

In [ ]:
batch_size = 256
train_ds = df_to_dataset(temp_train, batch_size=batch_size)
val_ds = df_to_dataset(temp_val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(temp_test, shuffle=False, batch_size=batch_size)

In [ ]:
all_inputs = []
encoded_features = []

# Numeric features.
for header in ['income_total', 'DAYS_BIRTH']:
  numeric_col = tf.keras.Input(shape=(1,), name=header)
  normalization_layer = get_normalization_layer(header, train_ds)
  encoded_numeric_col = normalization_layer(numeric_col)
  all_inputs.append(numeric_col)
  encoded_features.append(encoded_numeric_col)

In [ ]:
# Categorical features encoded as integers.
fam_col = tf.keras.Input(shape=(1,), name='family_size', dtype='int64')
encoding_layer = get_category_encoding_layer('family_size', train_ds, dtype='int64',
                                             max_tokens=5)
encoded_fam_col = encoding_layer(fam_col)
all_inputs.append(fam_col)
encoded_features.append(encoded_fam_col)

TypeError: ignored

In [ ]:
# Categorical features encoded as string.
categorical_cols = ['gender', 'car', 'reality', 'edu_type']
for header in categorical_cols:
  categorical_col = tf.keras.Input(shape=(1,), name=header, dtype='string')
  encoding_layer = get_category_encoding_layer(header, train_ds, dtype='string',
                                               max_tokens=5)
  encoded_categorical_col = encoding_layer(categorical_col)
  all_inputs.append(categorical_col)
  encoded_features.append(encoded_categorical_col)

모델 생성, 컴파일 및 훈련하기

In [ ]:
all_features = tf.keras.layers.concatenate(encoded_features)
x = tf.keras.layers.Dense(32, activation="relu")(all_features)
x = tf.keras.layers.Dropout(0.5)(x)
output = tf.keras.layers.Dense(1)(x)
model = tf.keras.Model(all_inputs, output)
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=["accuracy"])

모델 훈련하기

In [ ]:
model.fit(train_ds, epochs=10, validation_data=val_ds)

Epoch 1/10


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py:591: UserWarning: Input dict contained keys ['index', 'child_num', 'income_type', 'family_type', 'house_type', 'DAYS_EMPLOYED', 'FLAG_MOBIL', 'work_phone', 'phone', 'email', 'occyp_type', 'family_size', 'begin_month'] which did not match any model input. They will be ignored by the model.
  [n for n in tensors.keys() if n not in ref_input_names])


83/83 [==============================] - 1s 3ms/step - loss: -0.5333 - accuracy: 0.2169
Epoch 2/10
83/83 [==============================] - 0s 4ms/step - loss: -2.9164 - accuracy: 0.2386
Epoch 3/10
83/83 [==============================] - 0s 5ms/step - loss: -6.7825 - accuracy: 0.2386
Epoch 4/10
83/83 [==============================] - 0s 4ms/step - loss: -12.7383 - accuracy: 0.2386
Epoch 5/10
83/83 [==============================] - 0s 4ms/step - loss: -21.0026 - accuracy: 0.2386
Epoch 6/10
83/83 [==============================] - 0s 4ms/step - loss: -31.3734 - accuracy: 0.2386
Epoch 7/10
83/83 [==============================] - 0s 4ms/step - loss: -43.9206 - accuracy: 0.2386
Epoch 8/10
83/83 [==============================] - 0s 4ms/step - loss: -58.5396 - accuracy: 0.2386
Epoch 9/10
83/83 [==============================] - 0s 4ms/step - loss: -74.4941 - accuracy: 0.2386
Epoch 10/10
83/83 [==============================] - 0s 4ms/step - loss: -93.0193 - accuracy: 0.2386


명목형 변수 처리 - AutoEncoder  
(https://dacon.io/competitions/official/235713/codeshare/2562?page=3&dtype=recent) 참고

결측치 Nan 처리 & 레이블 인코딩


In [78]:
!pip install kaggler

     |████████████████████████████████| 829kB 7.0MB/s 
  Created wheel for kaggler: filename=Kaggler-0.9.6-cp37-cp37m-linux_x86_64.whl size=2959080 sha256=b22437df30b6d8d8fc6ef1883ddc974fc41881dbbea78d61cf5c1c2147edeafc
  Stored in directory: /root/.cache/pip/wheels/75/06/a9/f2a7b621e4c6b0571cec751c462683e7528d4fd0bb51060b4f
  Created wheel for ml-metrics: filename=ml_metrics-0.1.4-cp37-none-any.whl size=7850 sha256=7c49128d5c6a6bf04876d4a742078272e9af6664255aacfa2454418aae035973
  Stored in directory: /root/.cache/pip/wheels/b3/61/2d/776be7b8a4f14c5db48c8e5451451cabc58dc6aa7ee3801163
Successfully built kaggler ml-metrics


In [79]:
from kaggler.preprocessing import LabelEncoder
from kaggler.model import AutoLGB

In [82]:
index_col = 'index'
target_col = 'credit'

In [84]:
trn = pd.read_csv('/content/drive/MyDrive/creditcard/open/train.csv',index_col=index_col)
tst = pd.read_csv('/content/drive/MyDrive/creditcard/open/test.csv',index_col=index_col)
sub = pd.read_csv('/content/drive/MyDrive/creditcard/open/sample_submission.csv',index_col=index_col)


In [85]:
df = pd.concat([trn.drop(target_col, axis = 1),tst],axis=0)

In [86]:
cate_cols = [x for x in df.columns if df[x].dtype == 'object']
num_cols = [x for x in df.columns if x not in cate_cols + [target_col]]
feature_cols = num_cols + cate_cols
print(len(feature_cols), len(cate_cols), len(num_cols))

18 8 10


In [88]:
lbe = LabelEncoder(min_obs=10)
df[cate_cols] = lbe.fit_transform(df[cate_cols])
df[cate_cols].head()

gender  car  reality  ...  family_type  house_type  occyp_type
index                        ...                                     
0           0    0        1  ...            0           2           0
1           0    0        0  ...            2           0           1
2           1    1        0  ...            0           0           4
3           0    0        0  ...            0           0           3
4           0    1        0  ...            0           0           4

[5 rows x 8 columns]

autoencoder을 명목형 변수에만 해준 후 autolgbm 학습